// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "rpcmsg.pb.h"
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
// @@protoc_insertion_point(includes)

namespace wisc {
namespace RPCMsgProto {

void protobuf_ShutdownFile_rpcmsg_2eproto() {
  delete RPCMsg::default_instance_;
  delete RPCString::default_instance_;
  delete RPCWord::default_instance_;
  delete RPCStringArray::default_instance_;
  delete RPCWordArray::default_instance_;
}

void protobuf_AddDesc_rpcmsg_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  RPCMsg::default_instance_ = new RPCMsg();
  RPCString::default_instance_ = new RPCString();
  RPCWord::default_instance_ = new RPCWord();
  RPCStringArray::default_instance_ = new RPCStringArray();
  RPCWordArray::default_instance_ = new RPCWordArray();
  RPCMsg::default_instance_->InitAsDefaultInstance();
  RPCString::default_instance_->InitAsDefaultInstance();
  RPCWord::default_instance_->InitAsDefaultInstance();
  RPCStringArray::default_instance_->InitAsDefaultInstance();
  RPCWordArray::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_rpcmsg_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_rpcmsg_2eproto {
  StaticDescriptorInitializer_rpcmsg_2eproto() {
    protobuf_AddDesc_rpcmsg_2eproto();
  }
} static_descriptor_initializer_rpcmsg_2eproto_;


// ===================================================================

const ::std::string RPCMsg::_default_method_;
#ifndef _MSC_VER
const int RPCMsg::kMethodFieldNumber;
const int RPCMsg::kStringFieldsFieldNumber;
const int RPCMsg::kWordFieldsFieldNumber;
const int RPCMsg::kStringarrayFieldsFieldNumber;
const int RPCMsg::kWordarrayFieldsFieldNumber;
#endif  // !_MSC_VER

RPCMsg::RPCMsg()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void RPCMsg::InitAsDefaultInstance() {
}

RPCMsg::RPCMsg(const RPCMsg& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void RPCMsg::SharedCtor() {
  _cached_size_ = 0;
  method_ = const_cast< ::std::string*>(&_default_method_);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

RPCMsg::~RPCMsg() {
  SharedDtor();
}

void RPCMsg::SharedDtor() {
  if (method_ != &_default_method_) {
    delete method_;
  }
  if (this != default_instance_) {
  }
}

void RPCMsg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const RPCMsg& RPCMsg::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_rpcmsg_2eproto();  return *default_instance_;
}

RPCMsg* RPCMsg::default_instance_ = NULL;

RPCMsg* RPCMsg::New() const {
  return new RPCMsg;
}

void RPCMsg::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (_has_bit(0)) {
      if (method_ != &_default_method_) {
        method_->clear();
      }
    }
  }
  string_fields_.Clear();
  word_fields_.Clear();
  stringarray_fields_.Clear();
  wordarray_fields_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool RPCMsg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string method = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_method()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_string_fields;
        break;
      }
      
      // repeated .wisc.RPCMsgProto.RPCString string_fields = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_string_fields:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_string_fields()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_string_fields;
        if (input->ExpectTag(26)) goto parse_word_fields;
        break;
      }
      
      // repeated .wisc.RPCMsgProto.RPCWord word_fields = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_word_fields:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_word_fields()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_word_fields;
        if (input->ExpectTag(34)) goto parse_stringarray_fields;
        break;
      }
      
      // repeated .wisc.RPCMsgProto.RPCStringArray stringarray_fields = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_stringarray_fields:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_stringarray_fields()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_stringarray_fields;
        if (input->ExpectTag(42)) goto parse_wordarray_fields;
        break;
      }
      
      // repeated .wisc.RPCMsgProto.RPCWordArray wordarray_fields = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_wordarray_fields:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_wordarray_fields()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(42)) goto parse_wordarray_fields;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void RPCMsg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string method = 1;
  if (_has_bit(0)) {
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->method(), output);
  }
  
  // repeated .wisc.RPCMsgProto.RPCString string_fields = 2;
  for (int i = 0; i < this->string_fields_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      2, this->string_fields(i), output);
  }
  
  // repeated .wisc.RPCMsgProto.RPCWord word_fields = 3;
  for (int i = 0; i < this->word_fields_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      3, this->word_fields(i), output);
  }
  
  // repeated .wisc.RPCMsgProto.RPCStringArray stringarray_fields = 4;
  for (int i = 0; i < this->stringarray_fields_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      4, this->stringarray_fields(i), output);
  }
  
  // repeated .wisc.RPCMsgProto.RPCWordArray wordarray_fields = 5;
  for (int i = 0; i < this->wordarray_fields_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      5, this->wordarray_fields(i), output);
  }
  
}

int RPCMsg::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string method = 1;
    if (has_method()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->method());
    }
    
  }
  // repeated .wisc.RPCMsgProto.RPCString string_fields = 2;
  total_size += 1 * this->string_fields_size();
  for (int i = 0; i < this->string_fields_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->string_fields(i));
  }
  
  // repeated .wisc.RPCMsgProto.RPCWord word_fields = 3;
  total_size += 1 * this->word_fields_size();
  for (int i = 0; i < this->word_fields_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->word_fields(i));
  }
  
  // repeated .wisc.RPCMsgProto.RPCStringArray stringarray_fields = 4;
  total_size += 1 * this->stringarray_fields_size();
  for (int i = 0; i < this->stringarray_fields_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->stringarray_fields(i));
  }
  
  // repeated .wisc.RPCMsgProto.RPCWordArray wordarray_fields = 5;
  total_size += 1 * this->wordarray_fields_size();
  for (int i = 0; i < this->wordarray_fields_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->wordarray_fields(i));
  }
  
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void RPCMsg::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const RPCMsg*>(&from));
}

void RPCMsg::MergeFrom(const RPCMsg& from) {
  GOOGLE_CHECK_NE(&from, this);
  string_fields_.MergeFrom(from.string_fields_);
  word_fields_.MergeFrom(from.word_fields_);
  stringarray_fields_.MergeFrom(from.stringarray_fields_);
  wordarray_fields_.MergeFrom(from.wordarray_fields_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from._has_bit(0)) {
      set_method(from.method());
    }
  }
}

void RPCMsg::CopyFrom(const RPCMsg& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RPCMsg::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  
  for (int i = 0; i < string_fields_size(); i++) {
    if (!this->string_fields(i).IsInitialized()) return false;
  }
  for (int i = 0; i < word_fields_size(); i++) {
    if (!this->word_fields(i).IsInitialized()) return false;
  }
  for (int i = 0; i < stringarray_fields_size(); i++) {
    if (!this->stringarray_fields(i).IsInitialized()) return false;
  }
  for (int i = 0; i < wordarray_fields_size(); i++) {
    if (!this->wordarray_fields(i).IsInitialized()) return false;
  }
  return true;
}

void RPCMsg::Swap(RPCMsg* other) {
  if (other != this) {
    std::swap(method_, other->method_);
    string_fields_.Swap(&other->string_fields_);
    word_fields_.Swap(&other->word_fields_);
    stringarray_fields_.Swap(&other->stringarray_fields_);
    wordarray_fields_.Swap(&other->wordarray_fields_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string RPCMsg::GetTypeName() const {
  return "wisc.RPCMsgProto.RPCMsg";
}


// ===================================================================

const ::std::string RPCString::_default_name_;
const ::std::string RPCString::_default_value_;
#ifndef _MSC_VER
const int RPCString::kNameFieldNumber;
const int RPCString::kValueFieldNumber;
#endif  // !_MSC_VER

RPCString::RPCString()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void RPCString::InitAsDefaultInstance() {
}

RPCString::RPCString(const RPCString& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void RPCString::SharedCtor() {
  _cached_size_ = 0;
  name_ = const_cast< ::std::string*>(&_default_name_);
  value_ = const_cast< ::std::string*>(&_default_value_);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

RPCString::~RPCString() {
  SharedDtor();
}

void RPCString::SharedDtor() {
  if (name_ != &_default_name_) {
    delete name_;
  }
  if (value_ != &_default_value_) {
    delete value_;
  }
  if (this != default_instance_) {
  }
}

void RPCString::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const RPCString& RPCString::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_rpcmsg_2eproto();  return *default_instance_;
}

RPCString* RPCString::default_instance_ = NULL;

RPCString* RPCString::New() const {
  return new RPCString;
}

void RPCString::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (_has_bit(0)) {
      if (name_ != &_default_name_) {
        name_->clear();
      }
    }
    if (_has_bit(1)) {
      if (value_ != &_default_value_) {
        value_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool RPCString::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string name = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_value;
        break;
      }
      
      // required bytes value = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_value:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_value()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void RPCString::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string name = 1;
  if (_has_bit(0)) {
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->name(), output);
  }
  
  // required bytes value = 2;
  if (_has_bit(1)) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      2, this->value(), output);
  }
  
}

int RPCString::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string name = 1;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }
    
    // required bytes value = 2;
    if (has_value()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->value());
    }
    
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void RPCString::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const RPCString*>(&from));
}

void RPCString::MergeFrom(const RPCString& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from._has_bit(0)) {
      set_name(from.name());
    }
    if (from._has_bit(1)) {
      set_value(from.value());
    }
  }
}

void RPCString::CopyFrom(const RPCString& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RPCString::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  
  return true;
}

void RPCString::Swap(RPCString* other) {
  if (other != this) {
    std::swap(name_, other->name_);
    std::swap(value_, other->value_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string RPCString::GetTypeName() const {
  return "wisc.RPCMsgProto.RPCString";
}


// ===================================================================

const ::std::string RPCWord::_default_name_;
#ifndef _MSC_VER
const int RPCWord::kNameFieldNumber;
const int RPCWord::kValueFieldNumber;
#endif  // !_MSC_VER

RPCWord::RPCWord()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void RPCWord::InitAsDefaultInstance() {
}

RPCWord::RPCWord(const RPCWord& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void RPCWord::SharedCtor() {
  _cached_size_ = 0;
  name_ = const_cast< ::std::string*>(&_default_name_);
  value_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

RPCWord::~RPCWord() {
  SharedDtor();
}

void RPCWord::SharedDtor() {
  if (name_ != &_default_name_) {
    delete name_;
  }
  if (this != default_instance_) {
  }
}

void RPCWord::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const RPCWord& RPCWord::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_rpcmsg_2eproto();  return *default_instance_;
}

RPCWord* RPCWord::default_instance_ = NULL;

RPCWord* RPCWord::New() const {
  return new RPCWord;
}

void RPCWord::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (_has_bit(0)) {
      if (name_ != &_default_name_) {
        name_->clear();
      }
    }
    value_ = 0u;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool RPCWord::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string name = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_value;
        break;
      }
      
      // required uint32 value = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_value:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &value_)));
          _set_bit(1);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void RPCWord::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string name = 1;
  if (_has_bit(0)) {
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->name(), output);
  }
  
  // required uint32 value = 2;
  if (_has_bit(1)) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->value(), output);
  }
  
}

int RPCWord::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string name = 1;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }
    
    // required uint32 value = 2;
    if (has_value()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->value());
    }
    
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void RPCWord::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const RPCWord*>(&from));
}

void RPCWord::MergeFrom(const RPCWord& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from._has_bit(0)) {
      set_name(from.name());
    }
    if (from._has_bit(1)) {
      set_value(from.value());
    }
  }
}

void RPCWord::CopyFrom(const RPCWord& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RPCWord::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  
  return true;
}

void RPCWord::Swap(RPCWord* other) {
  if (other != this) {
    std::swap(name_, other->name_);
    std::swap(value_, other->value_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string RPCWord::GetTypeName() const {
  return "wisc.RPCMsgProto.RPCWord";
}


// ===================================================================

const ::std::string RPCStringArray::_default_name_;
#ifndef _MSC_VER
const int RPCStringArray::kNameFieldNumber;
const int RPCStringArray::kValueFieldNumber;
#endif  // !_MSC_VER

RPCStringArray::RPCStringArray()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void RPCStringArray::InitAsDefaultInstance() {
}

RPCStringArray::RPCStringArray(const RPCStringArray& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void RPCStringArray::SharedCtor() {
  _cached_size_ = 0;
  name_ = const_cast< ::std::string*>(&_default_name_);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

RPCStringArray::~RPCStringArray() {
  SharedDtor();
}

void RPCStringArray::SharedDtor() {
  if (name_ != &_default_name_) {
    delete name_;
  }
  if (this != default_instance_) {
  }
}

void RPCStringArray::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const RPCStringArray& RPCStringArray::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_rpcmsg_2eproto();  return *default_instance_;
}

RPCStringArray* RPCStringArray::default_instance_ = NULL;

RPCStringArray* RPCStringArray::New() const {
  return new RPCStringArray;
}

void RPCStringArray::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (_has_bit(0)) {
      if (name_ != &_default_name_) {
        name_->clear();
      }
    }
  }
  value_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool RPCStringArray::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string name = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_value;
        break;
      }
      
      // repeated bytes value = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_value:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->add_value()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_value;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void RPCStringArray::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string name = 1;
  if (_has_bit(0)) {
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->name(), output);
  }
  
  // repeated bytes value = 2;
  for (int i = 0; i < this->value_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      2, this->value(i), output);
  }
  
}

int RPCStringArray::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string name = 1;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }
    
  }
  // repeated bytes value = 2;
  total_size += 1 * this->value_size();
  for (int i = 0; i < this->value_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::BytesSize(
      this->value(i));
  }
  
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void RPCStringArray::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const RPCStringArray*>(&from));
}

void RPCStringArray::MergeFrom(const RPCStringArray& from) {
  GOOGLE_CHECK_NE(&from, this);
  value_.MergeFrom(from.value_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from._has_bit(0)) {
      set_name(from.name());
    }
  }
}

void RPCStringArray::CopyFrom(const RPCStringArray& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RPCStringArray::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  
  return true;
}

void RPCStringArray::Swap(RPCStringArray* other) {
  if (other != this) {
    std::swap(name_, other->name_);
    value_.Swap(&other->value_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string RPCStringArray::GetTypeName() const {
  return "wisc.RPCMsgProto.RPCStringArray";
}


// ===================================================================

const ::std::string RPCWordArray::_default_name_;
#ifndef _MSC_VER
const int RPCWordArray::kNameFieldNumber;
const int RPCWordArray::kValueFieldNumber;
#endif  // !_MSC_VER

RPCWordArray::RPCWordArray()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void RPCWordArray::InitAsDefaultInstance() {
}

RPCWordArray::RPCWordArray(const RPCWordArray& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void RPCWordArray::SharedCtor() {
  _cached_size_ = 0;
  name_ = const_cast< ::std::string*>(&_default_name_);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

RPCWordArray::~RPCWordArray() {
  SharedDtor();
}

void RPCWordArray::SharedDtor() {
  if (name_ != &_default_name_) {
    delete name_;
  }
  if (this != default_instance_) {
  }
}

void RPCWordArray::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const RPCWordArray& RPCWordArray::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_rpcmsg_2eproto();  return *default_instance_;
}

RPCWordArray* RPCWordArray::default_instance_ = NULL;

RPCWordArray* RPCWordArray::New() const {
  return new RPCWordArray;
}

void RPCWordArray::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (_has_bit(0)) {
      if (name_ != &_default_name_) {
        name_->clear();
      }
    }
  }
  value_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool RPCWordArray::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string name = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_value;
        break;
      }
      
      // repeated uint32 value = 2 [packed = true];
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_value:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, this->mutable_value())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 1, 18, input, this->mutable_value())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void RPCWordArray::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string name = 1;
  if (_has_bit(0)) {
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->name(), output);
  }
  
  // repeated uint32 value = 2 [packed = true];
  if (this->value_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(2, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_value_cached_byte_size_);
  }
  for (int i = 0; i < this->value_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32NoTag(
      this->value(i), output);
  }
  
}

int RPCWordArray::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string name = 1;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }
    
  }
  // repeated uint32 value = 2 [packed = true];
  {
    int data_size = 0;
    for (int i = 0; i < this->value_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        UInt32Size(this->value(i));
    }
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    _value_cached_byte_size_ = data_size;
    total_size += data_size;
  }
  
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void RPCWordArray::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const RPCWordArray*>(&from));
}

void RPCWordArray::MergeFrom(const RPCWordArray& from) {
  GOOGLE_CHECK_NE(&from, this);
  value_.MergeFrom(from.value_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from._has_bit(0)) {
      set_name(from.name());
    }
  }
}

void RPCWordArray::CopyFrom(const RPCWordArray& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RPCWordArray::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  
  return true;
}

void RPCWordArray::Swap(RPCWordArray* other) {
  if (other != this) {
    std::swap(name_, other->name_);
    value_.Swap(&other->value_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string RPCWordArray::GetTypeName() const {
  return "wisc.RPCMsgProto.RPCWordArray";
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace RPCMsgProto
}  // namespace wisc

// @@protoc_insertion_point(global_scope)
